name: Repository events
on: [push, pull_request, issues]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display GitHub Context
        run: |
          echo "Commit SHA: $GITHUB_SHA"
          echo "Reference: $GITHUB_REF"