name: External Events
on:
  repository_dispatch:

jobs:
  echo-a-string:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Repository Dispatch"
          echo ${{ github.event.client_payload.env }}
