name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Input description'
        type: string
        default: 'Kurman'
        required: false

jobs:
  calling-a-reusable-wf:
    uses: github-actions-1/workflows/.github/workflows/reusable.yaml@main
    with:
      name: ${{ inputs.name }}
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}