name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Input description'
        type: string
        default: 'Kurman'
        required: false
jobs:
  calling-a-reusable-wf:
    uses: github-actions-1/workflows/.github/workflows/reusable.yaml@main
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
  calling-a-reusable-wf-in-the-repo:
    uses: ./.github/workflows/reusable-workflow.yaml
    secrets: inherit
  using-reusable-wf-outputs:
    runs-on: ubuntu-latest
    needs: calling-a-reusable-wf-in-the-repo
    steps:
      - run: echo ${{ needs.calling-a-reusable-wf-in-the-repo.outputs.date }}